CompileFlags:
    Add:
      - -std=c++11
      - -Wall
      - -Werror
Diagnostics:
  ClangTidy:
    Add:
      - clang-analyzer-*
      - modernize-*
      - performance-*
      - readability-*
    Remove:
      - modernize-use-trailing-return-type
      - modernize-avoid-c-arrays
      - performance-no-int-to-ptr
      - readability-magic-numbers
      - readability-identifier-length
      - readability-function-cognitive-complexity
      - readability-implicit-bool-conversion
